name: Ruby

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Configurar Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true

    - name: Ejecutar linter
      run: bundle exec rubocop --fail-level C

    - name: Ejecutar pruebas
      run: bundle exec rspec
